FROM openjdk:8-alpine
COPY target/twitter*.jar /Users/apple/Desktop/GitHub/jarvis_data_eng_DeepakElango/core_java/twitter/target/twitter-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Users/apple/Desktop/GitHub/jarvis_data_eng_DeepakElango/core_java/twitter/target/twitter-1.0-SNAPSHOT.jar"]